name: MobWars
description: The minigame plugin where wars are fought between mobs!
version: 1.1
author: NathanApes

main: nathan.apes.mobwars.main.MobWars

commands:
  mw:
    description: Starts a game of MobWars, manually.
    usage: /mw
    permission: mobwars.game
  mwdisable:
    description: Disables all games of MobWars
    usage: /mwdisable
    permission: mobwars.game

permissions:
  mobwars.game:
    description: Gives access to game control.
    default: op
